### ISSUE TITLE
print node cause java.lang.StackOverflowError

### ISSUE THREAD

**Issue by oyxiaogua** [RutledgePaulV/prune#1]
```
create a tree,add some child element,then just print it,cause java.lang.StackOverflowError
`Tree.Node<Integer> root = new Tree.Node<>(1);
Tree.Node<Integer> child1 = new Tree.Node<>(2);
root.addChildrenNodes(child1);
System.out.println(root);`

 although i can use the following code to print a tree:
`Tree<Integer> tree = root.asTree();
 Stream<Integer> dept = tree.depthFirstStream();`

 i think it's best to override toString method.
```

**Comment by RutledgePaulV** [comment]
Holy crap. thanks :)

I'll get this fixed today.

**Comment by RutledgePaulV** [comment]
Thanks for this. It turned out to be the result of an unintentional cyclical reference in the auto-generated hashCode method. I took some time and corrected these equals and hashCode methods to reflect the behavior that is most likely intended when comparing nodes and trees. I also added tests to verify the fix.

Two nodes are equal if their data is equal.

Two trees are equal if each of their nodes are arranged in the same structure (including parent / child relationships and ordering) and each of the corresponding nodes are equal (their data is equal).

I also implemented better toString methods. 

Nodes which will just print the toString of their data. 

The toString of trees will produce an ascii representation of a tree (root on the left and depths extending to the right). The representation for each node in tree will just be the toString of the node.

You can get the fixed version with : 

``` xml
<dependencies>

    <dependency>
        <groupId>com.github.rutledgepaulv</groupId>
        <artifactId>prune</artifactId>
        <version>1.1</version>
    </dependency>

</dependencies>
```
